version: '3'

services:

  popular-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8000"
    command: "python api.py"
    env_file:
      - ./.env.docker

  redis:
    image: redis
    ports:
      - "6379:6379"







