import os

GITHUB_API_ACCESS_TOKEN = os.getenv("GITHUB_API_ACCESS_TOKEN")
GITHUB_API_URL = os.getenv("GITHUB_API_URL")
STAR_MULTIPLIER = int(os.getenv("STAR_MULTIPLIER", 1))
FORK_MULTIPLIER = int(os.getenv("FORK_MULTIPLIER", 2))
POPULAR_THRESHOLD = int(os.getenv("POPULAR_THRESHOLD", 500))
